### ISSUE TITLE
Stopped working on update

### ISSUE THREAD

**Issue by TheFrajem** [ERap320/LenovoWatchMOD#6] opened 2018-10-23 13:22 UTC
Hi, this morning I opened the app and it told me to update to 3.0.whatever, with no option whatsoever for not updating or doing it later. I had to click on update, and the update failed. Everytime I start the app, the window pops up again. The only way I found is to reinstall the app while offline and not run it again if online, but that's not so cool.
Any Idea?

**Comment by ERap320** [comment] 2018-10-23 17:27
Sadly updates are managed in a terribly wrong way by the developers.
You can't skip updates and you can't use the app if an update is available and you don't have the latest version.
My guess is that when you try to actually update it fails because it finds an inconsistency in the signage of the package. This happened from the first version and there is no way to avoid it.

Maybe someone more skilled than I am can try to disable update searching. I tried to do it but it also disabled the login functionality.

I do my best to provide a modded version as soon as a new official version comes out, but I don't have so much free time to do it immediately (I wish i did!).
Btw, version 3.0.2 of the mod will be up in minutes ;)

**Comment by zGitHubDev** [comment] 2019-01-18 23:44
Hi,

It is only a workaround suggestuin may work, and not too complicate to implement is try it. If you increase the version number to higher than the offical one, the updater may not try to download the new one,

**Comment by ERap320** [comment] 2019-01-19 07:58
Hi @zGitHubDev, thank you for the idea but I already tried it some time ago, and I tried again right now to confirm it does not work.
I changed every version number I could find in the decompiled application code, but I wasn't able to pin down the part of the code used to check if an update is available.
Maybe the app doesn't check for version number but for date of release, or something like that.

I'll surely go on trying to find ways to prevent this issue. If you want to help you'll be welcome to contribute.

**Comment by Glivmo** [comment] 2019-02-17 09:04
Hi, 

A new update (3.0.7) again stopped the app from working. Did you figure anything out to solve this indefinitely yet?

**Comment by ERap320** [comment] 2019-02-17 09:43
Hi @Glivmo, I haven't found yet a way to stop the forced updates.
Even worse news: the decompiled code of the new app is not as transparent as previous ones, so that I can't substitute apps as I used to do.

@zGitHubDev is decompiling in a different and more accurate way that lets him change tha Java code directly instead of messing with the smali like I was doing. Maybe he can work on that.
Sadly I'm very busy and I'm only able to develop this mod as long as it doesn't take much time.

I'll surely try to solve this myself by experimenting with some other tools, but I can't promise anything.

I would like to suggest using https://github.com/Freeyourgadget/Gadgetbridge until the issue is not solved (if you are using the Watch9, since the WatchX isn't supported yet).

**Comment by zGitHubDev** [comment] 2019-02-17 13:24
Hi,

I'm on holiday without any computer, I,m trying  to check it on next weeked. Until the workoround is to start the app without any net access and use the mod version without update.

**Comment by ERap320** [comment] 2019-02-19 19:14
I got to the bottom of the problem by taking the time to decompile the new APK with better tools.

Version 3.0.8 is protected by some kind of anti-decompiling measure that encrypts the source code. It seems to be developed by the chinese antivirus company "Quihoo360".

Seeing that we won't be able to mod v3.0.8 I did the necessary studying to prevent the forced updates in the last working version of the original app (3.0.3).
As a result of this, I pushed version 3.0.3_noupdate to this repository (https://github.com/ERap320/LenovoWatchMOD/commit/2b6fbf28b0477b7f9548cb1056328c3c14f7ed01).
Sadly, I don't think new versions will ever be released unless we find a way to go past the Quihoo encryption.

At least we now have a version that (should) work forever.

**Comment by mfj78** [comment] 2019-02-23 09:43
Great update! Will let you know if any issue occurs.

**Comment by zGitHubDev** [comment] 2019-02-24 00:03
Hi,

Unfortunately I have to agree with @ERap320  the app was somehow protected by Quihoo360 and my suspicion is that the source was moved to a server, and we can't access it. I'll use the new nonupdate app to update the Watch X plus branch. Thaks @ERap320.

**Comment by hhaliski** [comment] 2019-04-16 01:43
Did you tried mod this apk? Its an alternative to the Lenovo Watch app and have all the functions that the other app have... its basically the same but another UI.

IPowerful: https://play.google.com/store/apps/details?id=smart.p0000

**Comment by ERap320** [comment] 2019-12-24 09:08
A new version without Qihoo has been discovered and I have already released 3.1.0_noupdate. See #15.
It seemes this won't be a problem anymore, so I'm closing the issue for now.

**Closed by ERap320** 2019-12-24 09:08 UTC
Labels: announcement
